
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.0.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace CatGirlNet.RA2.Client.Console.UI {
    using Terminal.Gui;
    
    
    public partial class MainWindow {
        
        public MainWindow() {
            InitializeComponent();
        }
    }
}
